repos:
-   repo: https://github.com/python/black
    rev: master
    hooks:
    - id: black
      exclude: .venv*
      exclude_types: [directory,]
      language_version: python3.6
      log_file: precommit.log
      types: [file, python]
      args: [
            "--target-version=py36",
            "--exclude .venv*"
      ]
