language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
# command to install dependencies!
install:
  - "pip install -r requirements.txt"
  # - "pip install --upgrade python-dateutil pep8"
  - "pip install git+https://github.com/Guts/isogeo-api-py-minsdk"

# command to run tests!
script:
  - python -m unittest discover
  - pep8 isogeo_pysdk/isogeo_sdk.py --ignore="E265,E501" --statistics --show-source
