language: python
dist: xenial  # required for Python >= 3.7

git:
  depth: false
  submodules: false

matrix:
  include:
    - python: 3.6
    - python: 3.7

cache: pip

# dependencies
install:
  - "pip install --upgrade -r tests/requirements_test.txt"
  - pip install -e .

# run tests
script:
  # coverage
  - coverage run -m unittest discover -s tests/

# coverage reporting
after_success:
- codecov
