language: python

git:
  depth: false
  submodules: false

# https://docs.travis-ci.com/user/languages/python/#specifying-python-versions
python:
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)

cache: pip

# dependencies
install:
  - "pip install --upgrade -r tests/requirements_test.txt"

# run tests
script:
  # coverage
  - coverage run -m unittest discover -s tests/

# coverage reporting
after_success:
- codecov
