language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip

# dependencies
install:
  - "pip install --upgrade -r tests/requirements_test.txt"
  - "pip install git+https://github.com/Guts/isogeo-api-py-minsdk"

# run tests
script:
  - python -m unittest discover
  - pycodestyle isogeo_pysdk/isogeo_sdk.py --ignore="E265,E501" --statistics --show-source
  - pycodestyle isogeo_pysdk/checker.py --ignore="E265,E501" --statistics --show-source
  - pycodestyle isogeo_pysdk/utils.py --ignore="E265,E501" --statistics --show-source
