# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      pip install -U -r tests/requirements_test.txt
      coverage run -m unittest discover -s tests/
    env:
      ISOGEO_API_DEV_ID: $(ISOGEO_API_DEV_ID)
      ISOGEO_API_DEV_SECRET: $(ISOGEO_API_DEV_SECRET)
    displayName: 'Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Build'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python -m pip install -U pip && pip install -U -r requirements.txt
    displayName: 'Install dependencies'

  - script: python setup.py egg_info
    displayName: 'Build package metadata'

  - script: python setup.py sdist
    displayName: 'Build sdist'

  - script: python setup.py bdist_wheel
    displayName: 'Build wheel'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: IsogeoPySDK
      downloadPath: $(System.DefaultWorkingDirectory)/dist/
